identifier-prefix: icsm.profiles.

name: WA Implementation Profile for 3D CSDM
abstract: |
  This repository contains the working copy of the WA profile of the [Cadastral Survey Data Model Exchange Specification](https://icsm-au.github.io/3d-csdm-common/), 
  extending the  [common ICSM profile](https://icsm-au.github.io/3d-csdm-profile-icsm/).
   
  This version is being refined as required to meet the requirements of the WA Next Generation Spatial Cadastre

description: |

  The encoding specification and all profiles are compatible with the [OGC API Features](https://opengeospatial.github.io/e-learning/ogcapi-features/text/basic-main.html) data exchange specification, and can thus be implemented by any standards compliant software capable of handling nested object sub-schemas and control of codelist in content.
  
  Profiles are defined in a consistent, machine-readable and validatable way using the [OGC Building Blocks methodology](https://ogcincubator.github.io/bblocks-docs/).
  

imports:
  - default
  - https://surroundaustralia.github.io/3d-csdm-profile-icsm/build/register.json
#  - https://icsm-au.github.io/3d-csdm-common/build/register.json
#  - https://icsm-au.github.io/3d-csdm-profile-icsm/build/register.json
